### ISSUE TITLE
Mobile Application need create ?

### ISSUE THREAD

**Issue by mrshih** [tjwei/awesome-tw-foss#4]
請問iOS library要放在哪個大項呢？
或有需要開一個？順序又該擺在哪裡呢XD

**Comment by tjwei** [comment]
Mobile Application 這一個大項也有需要。 
不過如果是 library 的話，可以加在 Lib/Framework/API/Dev Tool 後面。
主要的分法是拿來怎麼用的。
目前 Dev這一項目前項目比較多，近期內會拆開或者整理出子項目。
