### ISSUE TITLE
awesome-watchos and awesome-rails-gem.

### ISSUE THREAD

**Issue by lockys** [tjwei/awesome-tw-foss#7]
https://github.com/yenchenlin1994/awesome-watchos
https://github.com/hothero/awesome-rails-gem

These two repos are also created and maintained by Taiwanese. :+1: 
Maybe it can be added into the Misc category.

**Comment by tjwei** [comment]
cool! mind to send a PR? or l will add them tomorrow.

**Comment by lockys** [comment]
OK, I have pull request :)
#8
